service: personal-site-api

configValidationMode: error

provider:
  name: aws
  region: ${self:custom.config.AWS_REGION}
  stage: ${opt:stage, 'local'}
  stackName: ${self:custom.baseName}
  runtime: nodejs14.x
  versionFunctions: false
  deploymentBucket:
    name: ${self:provider.stackName}-artifacts
  environment:
    NODE_OPTIONS: --enable-source-maps
  httpApi:
    disableDefaultEndpoint: true
    shouldStartNameWithService: true
    cors: true
   
package:
  individually: true

custom:
  baseName: ${self:service}-${self:provider.stage}
  config: ${file(./serverless.config.js):config}
  webpack:
    webpackConfig: './webpack.config.js'
    packager: yarn
  serverless-offline:
    httpPort: 4000
    useChildProcesses: true

functions:
  sendConnectEmail:
    handler: src/functions/sendConnectEmail.sendConnectEmail
    name: ${self:custom.baseName}-sendConnectEmailFunction
    events:
      - httpApi:
          method: GET
          path: /personal-site/connect
    environment:
      FROM_ADDRESS: ${self:custom.config.AWS_SES_FROM_ADDRESS}

resources:
  Resources:
    sendConnectEmailRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.baseName}-send-connect-email-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:custom.baseName}-send-connect-email-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: "Allow"
                  Action:
                    - "ses:SendRawEmail"
                  Resource: "*"

plugins:
  - serverless-deployment-bucket
  - serverless-webpack
  - serverless-offline