service: personal-site-api

configValidationMode: error

provider:
  name: aws
  region: ${file(./src/config.js):AWS_REGION}
  stage: ${opt:stage, 'local'}
  stackName: ${self:custom.baseName}
  runtime: nodejs14.x
  versionFunctions: false
  deploymentBucket:
    name: ${self:provider.stackName}-artifacts
  environment:
    NODE_OPTIONS: --enable-source-maps
  httpApi:
    disableDefaultEndpoint: true
    shouldStartNameWithService: true
    cors: true

package:
  individually: true

custom:
  baseName: ${self:service}-${self:provider.stage}
  webpack:
    webpackConfig: './webpack.config.js'
    packager: yarn
  serverless-offline:
    httpPort: 4000
    useChildProcesses: true

functions:
  sendConnectEmail:
    handler: src/functions/sendConnectEmail.sendConnectEmail
    name: ${self:custom.baseName}-sendConnectEmailFunction
    events:
      - httpApi:
          method: GET
          path: /sendConnectEmail

plugins:
  - serverless-deployment-bucket
  - serverless-domain-manager
  - serverless-webpack
  - serverless-offline