name: Deploy Prod To S3

on:
  push:
    branches:
      - "delivery"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: NPM Install
        run: npm install

      - name: Build App
        run: npm run build:prod

      - name: Deploy App to S3 Bucket
        run: aws s3 sync ./dist/personal-site/ s3://matthewthompson.us --delete

      - name: Configure Git
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'dawningfuture@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

      - name: Extract Version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6

      - name: Tag Version
        run: |
          git tag v${{ steps.extract_version.outputs.version }}
          git push origin v${{ steps.extract_version.outputs.version }}
