name: Deploy

on:
  push:
    branches:
      - "delivery"
      - "#114/deploy-aws-email-api"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: NPM Install
        run: yarn

      - name: Build app
        run: yarn workspace @ps/web run build:prod

      - name: Deploy static site to S3 bucket
        run: yarn workspace @ps/web run deploy

      - name: Invalidate CloudFront index.html
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }} \
            --paths "/index.html" \
            > /dev/null
