name: Deploy Staging To S3

on:
  create
  push:
    branches:
      - "staging/*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'refs/heads/staging/') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: NPM Install
        run: npm install

      - name: Build App
        run: npm run build:staging

      - name: Extract Version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6

      - name: Deploy App to S3 Bucket
        run: aws s3 sync ./dist/personal-site/ s3://staging.matthewthompson.us/${{ steps.extract_version.outputs.version }} --delete
