name: Deploy To S3

on:
  push:
    branches:
      - "delivery"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: NPM Install
        run: npm install

      - name: Build app
        run: npm run build:prod

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/personal-site/ s3://matthewthompson.us --delete
